"""Compatibility facade for dense Qdrant infrastructure."""

from app.errors import RetrievalError as RetrievalError
from app.infrastructure.qdrant import client as qdrant_client_adapter
from app.infrastructure.qdrant import dense as dense_infrastructure
from app.infrastructure.qdrant import manifests as dense_manifests

create_qdrant_client = qdrant_client_adapter.create_qdrant_client
build_embedding_text = dense_infrastructure.build_embedding_text
build_point_id = dense_infrastructure.build_point_id
create_embedding_model = dense_infrastructure.create_embedding_model
ensure_dense_collection = dense_infrastructure.ensure_dense_collection
get_embedding_dimension = dense_infrastructure.get_embedding_dimension
get_indexed_chunk_ids = dense_infrastructure.get_indexed_chunk_ids
index_chunks = dense_infrastructure.index_chunks
validate_dense_collection = dense_infrastructure.validate_dense_collection
_document_filter = dense_infrastructure.document_filter
_to_float_vector = dense_infrastructure.to_float_vector
dense_search = dense_infrastructure.dense_search
_retrieved_chunk_from_payload = dense_infrastructure._retrieved_chunk_from_payload
INDEX_MANIFEST_PATH = dense_manifests.INDEX_MANIFEST_PATH
validate_index_manifest = dense_manifests.validate_index_manifest
write_index_manifest = dense_manifests.write_index_manifest
